[package]
name = "logpeek-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
axum = "0.7.3"
lazy_static = "1.4.0"
log = "0.4.20"
logpeek = { path = "/home/fent/logpeek" }
mime_guess = "2.0.4"
regex = "1.10.2"
ringbuffer = "0.15.0"
rust-embed = "8.2.0"
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.56"
time = { version = "0.3.31", features = ["parsing"] }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.5.0", features = ["cors", "add-extension"] }
