[main]
buffer_size = 1_000_00 # The size of the log buffer that is kept in memory. When the buffer is full, the oldest logs are discarded.
address = "127.0.0.1:3001" # Host address of the server
secret = "asdf" # The password used for authentication. Removing this key will disable authentication.
buffer_update_cooldown = 10 # In seconds
max_login_attempts = 3 # The maximum number of login attempts before the client is blocked. Cleared by manual server restart.
allow_dirty_pagination = false # When true, paginating filtered logs will use the total, unfiltered log count. Saves CPU time.

[main.logger]
debug = false # When true, sets the minimum log level to debug
log_to_file = true # When true, logs will be written to a file
log_path = "testing-timeformat" # When log_to_file is true, logs will be written to this directory

[https]
enabled = false # When true, the server will use HTTPS
cert = "certs/localhost.pem" # The path to the certificate file, must be in PEM format
key = "certs/localhost-key.pem" # The path to the key file, must be in PEM format

[[application]]
path = "logpeek-logs" # Path to the application's log folder
parser = '''^(?P<timestamp>\S+) (?P<level>\S+) (?P<module>\S+) - (?P<message>.+)$''' # The regular expression used to parse the logs files of this application
timeformat = "iso8601" # The format of the timestamp in the logs. Supported formats are "iso8601", "rfc3339", "rfc2822" and custom.


[[application]]
path = "testing-timeformat"
parser = '''^(?P<timestamp>\S+) (?P<level>\S+) (?P<module>\S+) - (?P<message>.+)$'''
timeformat = "[year]-[month]-[day]|[hour]:[minute]:[second]|[offset_hour sign:mandatory]:[offset_minute]:[offset_second]"