# Config file for logpeek-server. Place this file in the same directory as the server executable.
# The values in this example config are the defaults.

# General configuration options.
[main]

# Host address of the server
address = "127.0.0.1:3001"

# The password used for authentication. Omitting this will disable authentication.
#secret = "replace_me"

# The maximum number of login attempts before the server is locked. Cleared by manual server restart.
max_login_attempts = 3

# The amount of seconds to not read in new log entires into the buffer for incoming requests.
buffer_update_cooldown = 10


[main.logger]
# When true, sets the minimum log level to debug
debug = false

# Whether to write log files
log_to_file = true

# When log_to_file is true, logs will be written to this directory
log_path = "logpeek-logs"


# HTTPS is supported, altough a reverse proxy will almost always offer more options.
[https]
# When true, the server will try to use HTTPS
enabled = false

# The path to the certificate file, must be in PEM format and unencrypted
cert = "path/to/cert.pem"

# The path to the key file, must be in PEM format and unencrypted
key = "path/to/key.pem"


# List of applications whose log files will be monitored. Each application must have a path, a respective parser, the timeformat and optional buffer_size.
[[application]]
# Path to the application's log folder.
path = "logpeek-logs"

# The regular expression used to parse the logs files of this application.
# At the moment, all capture groups present in the example below must be included.
parser = '''^(?P<timestamp>\S+) (?P<level>\S+) (?P<module>\S+) - (?P<message>.+)$'''

# The format of the timestamp in the logs. Supported formats are "iso8601", "rfc3339", "rfc2822" and custom.
# Altough custom timeformats are supported, built-in formats should be preferred.
# Since UTC is used internally, the timeformat must include an offset. Minimum example for a custom timeformat: "[year]-[month]-[day]|[hour]|[offset_hour]"
# Refer to https://time-rs.github.io/book/api/format-description.html (version 1) for possible options.
timeformat = "iso8601"

# The size of the log buffer that is kept in memory. When the buffer is full, the oldest logs are discarded first.
buffer_size = 1_000_000

# There is no limit to the amount of applications that can be monitored at once.
# Simply add another [[application]] section with the same fields as above.